### ISSUE TITLE
希望慢图浏览可以对接阿里云的接口

### ISSUE THREAD

**Issue by lvluozixuemengyanyan** [RelaxPic/relaxpic.github.io#4]
希望慢图浏览可以对接阿里云的接口，这样一来，就可以用阿里云账号直接登录了，少不少弯弯绕`·····

**Comment by RelaxPic** [comment]
> 希望慢图浏览可以对接阿里云的接口，这样一来，就可以用阿里云账号直接登录了，少不少弯弯绕`·····


暂时没有该计划。

目前只考虑webdav，最好是自建。 即使是使用Alist接入的第三方webdav， 也会对应用造成不好的体验。 
比如查询太慢， webdav 的Depth不支持infinity 等, 还有流量被限制等。 

如果Depth 不支持infinity , 那么用户手机里面的照片判断云端是否存在，有2w张要发送2w个请求吗？  


再举个例子比如坚果云的限制， 首先是单个文件夹返回的文件数量超过1000多就随机不返回了，  这种服务商就更加难受了。

这里我明确告知慢图浏览最好使用自建 WebDAV， Alist或者其他第三方提供的dav服务源很可能带来不可预估的错误。
