### ISSUE TITLE
Webdav同步问题

### ISSUE THREAD

**Issue by Renjiu13** [RelaxPic/relaxpic.github.io#5]
很棒的软件，我很喜欢。在设置中我没有找到同步功能，请问是这个功能是暂时维护了嘛？

**Comment by RelaxPic** [comment]
回归时间待定

**Comment by wan0ge** [comment]
> 回归时间待定

很多早期的推荐宣传都写着支持WebDav，打开一看找半天没看见原来是砍了😢 什么原因这是
![Image](https://github.com/user-attachments/assets/51a688ef-1414-4a50-b008-597a980ab2f0)
